name: DUB Photography
favicon: null
layout_spectrum: 0.3456031659152359
typography_spectrum: 0.12879037880338728
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f4f8'
    - '#252620'
    - '#777c8f'
    - '#d9c7d7'
    - '#b39ab0'
  brandStrength: 0.36968191037885845
  lightness: 0.10138935735449195
  saturation: 0.6087524287868291
  rhythmicContrast: 0.705865386640653
purpose: []
